### ISSUE TITLE
nth-child helper

### ISSUE THREAD

**Issue by dbox** [kni-labs/knapsack#14]
@trevasco has idea for simpilfying nth child stuff

` @for $i from 1 through n`

Can you expound?

**Comment by dbox** [comment]
I'm trying to think how we could even do a mixin that would be flexible enough to work with any situation. 

Maybe better just to have an example we can always reference.

``` scss
$max-items: 12;
@for $i from 1 through $max-items {
  $delay: $i * .08s;
  &:nth-child(#{$i}) {
    animation-delay: $delay;
  }
}
```

@trevasco would you mind posting 1 or 2 examples of how you've used it recently?

**Comment by trevasco** [comment]
```css
@for $i from 1 through 10 {
  &.is-selected {
    visibility: visible;

    article:nth-child(#{$i}) {
      opacity: 1;
      transition-delay: ($i * 0.15) + s;
    }
  }
}
```

also I think it would be sweet to have a mixin that you could just pass colors into, and then determine if its a background or color property, or both, and if hover is needed

```css
$bg: #51b54e, #35823b, #62a142, #abcc52,
     #cbda5a, #580c23, #b4214a, #dd3f3a,
     #eb5b30, #f38030, #d0d9c7, #82b4ed;

@for $i from 1 through length($bg) {
   &:nth-of-type( #{length($bg)}n + #{$i} ) {
     background: nth($bg, $i);
     &:hover { background: lighten(nth($bg, $i), 7%); }
   }
 }
```
