### ISSUE TITLE
psuedo element jumpstart

### ISSUE THREAD

**Issue by dbox** [kni-labs/knapsack#20]
Seems like a lot of times we could speed up process of adding psuedo elements with this:

```scss
@mixin pseudo() {
  position: absolute;
  content: '';
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```
not sure if name is right or not..
