### ISSUE TITLE
cover

### ISSUE THREAD

**Issue by dbox** [kni-labs/knapsack#21]
From @trevasco :

```scss
@mixin cover() {
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
}
```

**Comment by dbox** [comment]
Perhaps it should it be:

``` scss
@mixin cover($x: center, $y: center) {
  width: 100%;
  height: 100%;
  background-size: cover;
  background-repeat: no-repeat;
  background-position: $x $y;
}
```
