### ISSUE TITLE
Ratio-box additions

### ISSUE THREAD

**Issue by dbox** [kni-labs/knapsack#22]
Neat idea via @corysimmons:
```scss
  > * {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
``` 
Since all interior content has to be absolute anyway.
