### ISSUE TITLE
absolute center fix

### ISSUE THREAD

**Issue by dbox** [kni-labs/knapsack#29]
Current:
``` scss
@mixin absolute-center($width: 50%) {
  left: 0;
  margin-left: auto;
  margin-right: auto;
  position: absolute;
  right: 0;
  width: $width;
}
```

proposed:

``` scss
@mixin absolute-center($width: 50%) {
  left: 0;
  margin-left: auto;
  margin-right: auto;
  max-width: $width;  // better for responsive
  position: absolute;
  right: 0;
  width: 100%;  // better for responsive

}
```
