### ISSUE TITLE
Absolute center

### ISSUE THREAD

**Issue by dbox** [kni-labs/knapsack#8]
``` scss
@mixin absolute-center($width: 50%) {
  left: 0;
  margin-left: auto;
  margin-right: auto;
  position: absolute;  
  right: 0;
  width: $width;
}
```
