### ISSUE TITLE
%placeholders

### ISSUE THREAD

**Issue by dbox** [kni-labs/knapsack#9]
Might be nice to have a section for commonly used placeholders:

ie:
``` scss
%hide-below-tablet {
  @media (max-width: 767px) {
    display: none;
  }
}
```
